import Head from "next/head";
import {
  Text,
  Container,
  Grid,
  GridItem,
  Flex,
  Button,
  Image,
  Box,
  Center,
} from "@chakra-ui/react";

import Link from "next/link";

const Home = () => {
  return (
    <>
      <Head>
        <title>Simple Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl">
        <Center>
          <Grid
            templateRows="repeat(1, 1fr)"
            templateColumns="repeat(1, 1fr)"
            gap={5}
            pt={{ base: "3", md: "5", lg: "7" }}
          >
            <GridItem colSpan={1} pt={10}>
              <Center pb={7}>
                <Image
                  src="/assets/images/logo-box.png"
                  alt="mimic_finance"
                  width="140px"
                />
              </Center>
              <Center>
                <Text className="text-primary home-title">
                  Simple <text className="text-normal">Bank</text>
                </Text>
              </Center>
              <Text className="home-subtitle text-normal">
                <Center>The New Decentralized Bank</Center>
              </Text>
              <Text className="text-normal" mt={7}>
                <Center style={{ textAlign: "center" }}>
                  Make easy deposit and withdraw & Easy transfer to other
                  account
                </Center>
              </Text>
            </GridItem>
            <GridItem colSpan={1}>
              <Center>
                <Flex>
                  <Grid
                    templateRows="repeat(1, 1fr)"
                    templateColumns="repeat(2, 1fr)"
                    gap={5}
                    pt={{ base: "2", md: "4", lg: "7" }}
                  >
                    <GridItem colSpan={2}>
                      <Link href="/app" passHref>
                        <Button
                          style={{
                            color: "#FFFFFF",
                            background:
                              "linear-gradient(90deg ,#576cea 0%, #da65d1 100%)",
                          }}
                        >
                          Launch App
                        </Button>
                      </Link>
                    </GridItem>
                  </Grid>
                </Flex>
              </Center>
            </GridItem>
          </Grid>
        </Center>
      </Container>
    </>
  );
};

export default Home;
